version: "3.9"

services:
  main_server:
    depends_on:
      - redis
      # - chroma
    image: qyzhizi/memoflow:v0.1.5

    ports:
     - "8080:8080"
     - "6789:6789"
    # restart: always
    volumes:
      - "..:/app"
    networks:
      - net
    command: >
      sh -c "python memoflow/cmd/celery_work > celery_work.log 2>&1 &
             python -m debugpy --listen 0.0.0.0:6789 --wait-for-client  memoflow/cmd/main"
  redis:
    image: "redis/redis-stack-server:latest"
    networks:
      - net   

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/chroma
    command: "--workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"

    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=False
      - ALLOW_RESET=True
      - REBUILD_HNSWLIB=False
    networks:
      - net
  
networks:
  net:
    driver: bridge
