version: "3.9"

services:
  main_server:
    depends_on:
      - redis
    image: qyzhizi/memoflow:v0.1.5
    env_file:
      - ../.env
    ports:
     - "6060:6060"
    volumes:
      - "../.env:/app/.env"
      - "../log_file:/app/log_file"
      - "../db_data:/app/db_data"
    networks:
      - net    
    restart: on-failure
    command:  sh -c "python setup.py egg_info && sh memoflow/cmd/run.sh"   

  redis:
    image: "redis/redis-stack-server:latest"
    networks:
      - net 
    restart: on-failure

networks:
  net:
    driver: bridge
