version: "3.9"

services:
  main_server:
    depends_on:
      - redis
      - chroma
    image: qyzhizi/memoflow:v0.1.5

    ports:
     - "9000:9000"
     - "5678:5678"
    restart: always
    volumes:
      - "..:/app"
    networks:
      - net
    command: >
      sh -c "python memoflow/cmd/celery_work > celery_work.log 2>&1 &
             python -m debugpy --listen 0.0.0.0:5678 --wait-for-client  memoflow/cmd/main"
  redis:
    image: "redis/redis-stack-server:latest"
    networks:
      - net   

  chroma:
    image: qyzhizi/chroma:latest
    volumes:
      - ../db_data/chroma_persist:/chroma/chroma
    # ports:
    #   - 8000:8000
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=False
      - ALLOW_RESET=True
    networks:
      - net
  
networks:
  net:
    driver: bridge
