version: "3.9"

services:
  main_server:
    depends_on:
      - redis
    build: ./
    env_file:
      - .env
    ports:
     - "9000:9000"
    restart: always
    volumes:
      - ".:/app"
  redis:
    image: "redis/redis-stack-server:latest"
