version: "3.9"

services:
  main_server:
    depends_on:
      - redis
    build: ./
    # image: web_dl-main_server:latest
    ports:
     - "9000:9000"
     - "5678:5678"
    restart: always
    volumes:
      - ".:/app"
    command: >
      sh -c "python memoflow/cmd/celery_work > celery_work.log 2>&1 &
             python -m debugpy --listen 0.0.0.0:5678 --wait-for-client  memoflow/cmd/main"
  redis:
    image: "redis/redis-stack-server:latest"
