version: "3.9"

services:
  main_server:
    depends_on:
      - redis
    # build: ./
    image: memoflow:v0.1.2
    env_file:
      - .env
    ports:
     - "9000:9000"
    volumes:
      - ".:/app"
  redis:
    image: "redis/redis-stack-server:latest"
