version: "3.9"

services:
  main_server:
    depends_on:
      - redis
      - chroma
    build: ./
    # image: qyzhizi/memoflow:v0.1.4
    env_file:
      - .env
    ports:
     - "9000:9000"
    volumes:
      - ".:/app"
    networks:
      - net  

  redis:
    image: "redis/redis-stack-server:latest"
    networks:
      - net 

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      # - ../db_data/chroma_persist:/chroma/chroma
      - index_data:/chroma/chroma
    ports:
      - 8001:8000
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=False
      - ALLOW_RESET=True    
    networks:
      - net

volumes:
  index_data:
    driver: local

networks:
  net:
    driver: bridge
