version: '3'

services:
  traefik:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http_web.address=:80
      - --entrypoints.https_web.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "./traefik.yml:/traefik.yml:ro"
    networks:
      - traefik

networks:
  traefik:
    driver: bridge
